packages:
  - packages/*
  - packages/adapters/*
  - packages/plugins/*
  - packages/plugins/examples/*
  - packages/plugins/plugin-firecrawl
  - packages/plugins/plugin-twitter
  - packages/plugins/plugin-discord
  - server
  - ui
  - cli
