import { Router } from "express";
import type { Db } from "@paperclipai/db";
import { contentService } from "../services/content.js";
import { contentFeedbackService } from "../services/content-feedback.js";
import { logger } from "../middleware/logger.js";

// ---------------------------------------------------------------------------
// Auth helper — content endpoints require CONTENT_API_KEY
// ---------------------------------------------------------------------------

const CONTENT_API_KEY = process.env.CONTENT_API_KEY || "";

function requireContentKey(
  req: import("express").Request,
  res: import("express").Response,
  next: import("express").NextFunction,
) {
  if (!CONTENT_API_KEY) {
    res.status(503).json({ error: "Content API key not configured" });
    return;
  }
  const provided =
    req.headers["x-content-key"] as string | undefined ??
    req.headers["authorization"]?.replace("Bearer ", "");
  if (provided !== CONTENT_API_KEY) {
    res.status(401).json({ error: "Invalid or missing content API key" });
    return;
  }
  next();
}

// ---------------------------------------------------------------------------
// Public rate limiter — 5 requests per IP per hour, no deps
// ---------------------------------------------------------------------------

const publicRateLimits = new Map<string, { count: number; resetAt: number }>();
const PUBLIC_RATE_LIMIT = 5;
const PUBLIC_RATE_WINDOW_MS = 60 * 60 * 1000; // 1 hour

function checkPublicRateLimit(ip: string): boolean {
  const now = Date.now();
  const entry = publicRateLimits.get(ip);
  if (!entry || now > entry.resetAt) {
    publicRateLimits.set(ip, { count: 1, resetAt: now + PUBLIC_RATE_WINDOW_MS });
    return true;
  }
  if (entry.count >= PUBLIC_RATE_LIMIT) return false;
  entry.count++;
  return true;
}

// Cleanup stale entries every 10 minutes
setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of publicRateLimits) {
    if (now > entry.resetAt) publicRateLimits.delete(ip);
  }
}, 10 * 60 * 1000);

// Metadata footer appended to all public-generated content
const ATTRIBUTION_FOOTER: Record<string, string> = {
  tweet: "\n\n🔗 coherencedaddy.com",
  thread: "\n\n🔗 Data from coherencedaddy.com | Free tools at freetools.coherencedaddy.com",
  blog_post: "\n\n---\n*Generated by [Coherence Daddy Intel Engine](https://coherencedaddy.com) — free AI-powered crypto & tech intelligence.*",
  linkedin: "\n\n🔗 Generated with Coherence Daddy Intel Engine | coherencedaddy.com",
  reddit: "\n\n---\n*Data powered by [Coherence Daddy](https://coherencedaddy.com) — free crypto & AI intel tools.*",
  bluesky: "\n\n🔗 coherencedaddy.com",
  discord: "\n\n🔗 Data from coherencedaddy.com",
};

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

export function contentRoutes(db: Db) {
  const router = Router();
  const svc = contentService(db);
  const feedbackSvc = contentFeedbackService(db);

  // ---- PUBLIC: POST /api/content/public/generate ----
  // No auth required, rate-limited, preview-only (does not save to DB)

  router.post("/public/generate", async (req, res) => {
    const ip = req.ip || req.socket.remoteAddress || "unknown";

    if (!checkPublicRateLimit(ip)) {
      res.status(429).json({
        error: "Rate limit exceeded. Free tier allows 5 generations per hour.",
        retryAfter: "1 hour",
      });
      return;
    }

    const { topic, platform, personality } = req.body as {
      topic?: string;
      platform?: string;
      personality?: string;
    };

    if (!topic || !platform) {
      res.status(400).json({ error: "Missing required fields: topic, platform" });
      return;
    }

    const validPlatforms = ["tweet", "thread", "blog_post", "linkedin", "reddit", "bluesky", "discord"];
    if (!validPlatforms.includes(platform)) {
      res.status(400).json({ error: `Invalid platform. Valid: ${validPlatforms.join(", ")}` });
      return;
    }

    const personalityId = personality || "blaze";

    try {
      const result = await svc.preview({
        personalityId,
        contentType: platform,
        topic,
        contextQuery: topic,
      });

      // Append attribution footer
      const footer = ATTRIBUTION_FOOTER[platform] || ATTRIBUTION_FOOTER.tweet;
      const contentWithAttribution = result.content + footer;

      res.json({
        content: contentWithAttribution,
        contentRaw: result.content,
        metadata: {
          ...result.metadata,
          attribution: "Coherence Daddy Intel Engine",
          source: "https://coherencedaddy.com",
          tools: "https://freetools.coherencedaddy.com",
        },
        platform,
        personality: personalityId,
      });
    } catch (err) {
      logger.error({ err, topic, platform }, "Public content generation error");
      res.status(500).json({ error: "Generation failed. Please try again." });
    }
  });

  // ---- POST /api/content/preview ----

  router.post("/preview", requireContentKey, async (req, res) => {
    const { personalityId, contentType, topic, contextQuery } = req.body;

    if (!personalityId || !contentType || !topic) {
      res.status(400).json({
        error: "Missing required fields: personalityId, contentType, topic",
      });
      return;
    }

    try {
      const result = await svc.preview({ personalityId, contentType, topic, contextQuery });
      res.json(result);
    } catch (err) {
      logger.error({ err }, "Content preview error");
      res.status(500).json({ error: String(err) });
    }
  });

  // ---- POST /api/content/generate ----

  router.post("/generate", requireContentKey, async (req, res) => {
    const { personalityId, contentType, topic, contextQuery } = req.body;

    if (!personalityId || !contentType || !topic) {
      res.status(400).json({
        error: "Missing required fields: personalityId, contentType, topic",
      });
      return;
    }

    try {
      const result = await svc.generate({ personalityId, contentType, topic, contextQuery });
      res.json(result);
    } catch (err) {
      logger.error({ err }, "Content generation error");
      res.status(500).json({ error: String(err) });
    }
  });

  // ---- GET /api/content/queue ----

  router.get("/queue", requireContentKey, async (req, res) => {
    const status = req.query.status as string | undefined;
    const platform = req.query.platform as string | undefined;
    const limit = Math.min(
      Math.max(1, parseInt(req.query.limit as string ?? "50", 10) || 50),
      200,
    );
    const offset = Math.max(0, parseInt(req.query.offset as string ?? "0", 10) || 0);

    try {
      const items = await svc.listQueue({ status, platform, limit, offset });
      res.json({ items, count: items.length, limit, offset });
    } catch (err) {
      logger.error({ err }, "Content queue list error");
      res.status(500).json({ error: "Failed to list content queue" });
    }
  });

  // ---- PATCH /api/content/queue/:id/review ----

  router.patch("/queue/:id/review", requireContentKey, async (req, res) => {
    const id = req.params.id as string;
    const reviewStatus = req.body.reviewStatus as string;
    const reviewComment = req.body.reviewComment as string | undefined;

    if (!reviewStatus) {
      res.status(400).json({ error: "Missing required field: reviewStatus" });
      return;
    }

    try {
      await svc.reviewItem(id, reviewStatus, reviewComment);
      res.json({ success: true, id, reviewStatus });
    } catch (err) {
      logger.error({ err, id }, "Content review error");
      const message = err instanceof Error ? err.message : String(err);
      const status = message.includes("not found") ? 404 : 400;
      res.status(status).json({ error: message });
    }
  });

  // ---- GET /api/content/queue/stats ----

  router.get("/queue/stats", requireContentKey, async (_req, res) => {
    try {
      const result = await svc.stats();
      res.json(result);
    } catch (err) {
      logger.error({ err }, "Content stats error");
      res.status(500).json({ error: "Stats unavailable" });
    }
  });

  // ---- POST /api/content/:id/feedback ----

  router.post("/:id/feedback", requireContentKey, async (req, res) => {
    const contentItemId = req.params.id as string;
    const { rating, comment, contentType } = req.body as {
      rating: string;
      comment?: string;
      contentType?: string;
    };

    if (!rating || (rating !== "like" && rating !== "dislike")) {
      res.status(400).json({ error: 'Missing or invalid rating. Must be "like" or "dislike"' });
      return;
    }

    const companyId = process.env.TEAM_DASHBOARD_COMPANY_ID || "8365d8c2-ea73-4c04-af78-a7db3ee7ecd4";

    try {
      const feedback = await feedbackSvc.add({
        companyId,
        contentItemId,
        contentType: (contentType as "text" | "visual") || "text",
        rating: rating as "like" | "dislike",
        comment,
        createdByUserId: req.actor?.type === "board" ? req.actor.userId ?? undefined : undefined,
      });
      res.json(feedback);
    } catch (err) {
      logger.error({ err, contentItemId }, "Content feedback error");
      res.status(500).json({ error: "Failed to submit feedback" });
    }
  });

  // ---- GET /api/content/:id/feedback ----

  router.get("/:id/feedback", requireContentKey, async (req, res) => {
    const contentItemId = req.params.id as string;

    try {
      const feedback = await feedbackSvc.getForItem(contentItemId);
      res.json({ feedback });
    } catch (err) {
      logger.error({ err, contentItemId }, "Content feedback list error");
      res.status(500).json({ error: "Failed to fetch feedback" });
    }
  });

  // ---- GET /api/content/feedback/stats ----

  router.get("/feedback/stats", requireContentKey, async (_req, res) => {
    const companyId = process.env.TEAM_DASHBOARD_COMPANY_ID || "8365d8c2-ea73-4c04-af78-a7db3ee7ecd4";

    try {
      const stats = await feedbackSvc.getStats(companyId);
      res.json(stats);
    } catch (err) {
      logger.error({ err }, "Content feedback stats error");
      res.status(500).json({ error: "Failed to fetch feedback stats" });
    }
  });

  return router;
}
