import { Router } from "express";
import { sql, eq, desc, count } from "drizzle-orm";
import { createHash } from "crypto";
import type { Db } from "@paperclipai/db";
import { contentItems, contentClicks } from "@paperclipai/db";
import { contentService } from "../services/content.js";
import { contentFeedbackService } from "../services/content-feedback.js";
import { recordNegativeFeedback, recordPositiveFeedback } from "../services/intel-quality.js";
import {
  buildBlogPostFromContent,
  republishTarget,
  type BlogPost,
} from "../services/blog-publisher.js";
import { logger } from "../middleware/logger.js";

// ---------------------------------------------------------------------------
// Auth helper — content endpoints require CONTENT_API_KEY
// ---------------------------------------------------------------------------

const CONTENT_API_KEY = process.env.CONTENT_API_KEY || "";

function requireContentKey(
  req: import("express").Request,
  res: import("express").Response,
  next: import("express").NextFunction,
) {
  // Board (session) users always pass — they're already authenticated via the actor middleware
  if (req.actor?.type === "board") {
    next();
    return;
  }
  if (!CONTENT_API_KEY) {
    res.status(503).json({ error: "Content API key not configured" });
    return;
  }
  const provided =
    req.headers["x-content-key"] as string | undefined ??
    req.headers["authorization"]?.replace("Bearer ", "");
  if (provided !== CONTENT_API_KEY) {
    res.status(401).json({ error: "Invalid or missing content API key" });
    return;
  }
  next();
}

// ---------------------------------------------------------------------------
// Public rate limiter — 5 requests per IP per hour, no deps
// ---------------------------------------------------------------------------

const publicRateLimits = new Map<string, { count: number; resetAt: number }>();
const PUBLIC_RATE_LIMIT = 5;
const PUBLIC_RATE_WINDOW_MS = 60 * 60 * 1000; // 1 hour

function checkPublicRateLimit(ip: string): boolean {
  const now = Date.now();
  const entry = publicRateLimits.get(ip);
  if (!entry || now > entry.resetAt) {
    publicRateLimits.set(ip, { count: 1, resetAt: now + PUBLIC_RATE_WINDOW_MS });
    return true;
  }
  if (entry.count >= PUBLIC_RATE_LIMIT) return false;
  entry.count++;
  return true;
}

// Cleanup stale entries every 10 minutes
setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of publicRateLimits) {
    if (now > entry.resetAt) publicRateLimits.delete(ip);
  }
}, 10 * 60 * 1000);

// Metadata footer appended to all public-generated content
const ATTRIBUTION_FOOTER: Record<string, string> = {
  tweet: "\n\n🔗 coherencedaddy.com",
  thread: "\n\n🔗 Data from coherencedaddy.com | Free tools at freetools.coherencedaddy.com",
  blog_post: "\n\n---\n*Generated by [Coherence Daddy Intel Engine](https://coherencedaddy.com) — free AI-powered crypto & tech intelligence.*",
  linkedin: "\n\n🔗 Generated with Coherence Daddy Intel Engine | coherencedaddy.com",
  reddit: "\n\n---\n*Data powered by [Coherence Daddy](https://coherencedaddy.com) — free crypto & AI intel tools.*",
  bluesky: "\n\n🔗 coherencedaddy.com",
  discord: "\n\n🔗 Data from coherencedaddy.com",
};

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

export function contentRoutes(db: Db) {
  const router = Router();
  const svc = contentService(db);
  const feedbackSvc = contentFeedbackService(db);

  // ---- PUBLIC: POST /api/content/public/generate ----
  // No auth required, rate-limited, preview-only (does not save to DB)

  router.post("/public/generate", async (req, res) => {
    const ip = req.ip || req.socket.remoteAddress || "unknown";

    if (!checkPublicRateLimit(ip)) {
      res.status(429).json({
        error: "Rate limit exceeded. Free tier allows 5 generations per hour.",
        retryAfter: "1 hour",
      });
      return;
    }

    const { topic, platform, personality } = req.body as {
      topic?: string;
      platform?: string;
      personality?: string;
    };

    if (!topic || !platform) {
      res.status(400).json({ error: "Missing required fields: topic, platform" });
      return;
    }

    const validPlatforms = ["tweet", "thread", "blog_post", "linkedin", "reddit", "bluesky", "discord"];
    if (!validPlatforms.includes(platform)) {
      res.status(400).json({ error: `Invalid platform. Valid: ${validPlatforms.join(", ")}` });
      return;
    }

    const personalityId = personality || "blaze";

    try {
      const result = await svc.preview({
        personalityId,
        contentType: platform,
        topic,
        contextQuery: topic,
      });

      // Append attribution footer
      const footer = ATTRIBUTION_FOOTER[platform] || ATTRIBUTION_FOOTER.tweet;
      const contentWithAttribution = result.content + footer;

      res.json({
        content: contentWithAttribution,
        contentRaw: result.content,
        metadata: {
          ...result.metadata,
          attribution: "Coherence Daddy Intel Engine",
          source: "https://coherencedaddy.com",
          tools: "https://freetools.coherencedaddy.com",
        },
        platform,
        personality: personalityId,
      });
    } catch (err) {
      logger.error({ err, topic, platform }, "Public content generation error");
      res.status(500).json({ error: "Generation failed. Please try again." });
    }
  });

  // ---- POST /api/content/preview ----

  router.post("/preview", requireContentKey, async (req, res) => {
    const { personalityId, contentType, topic, contextQuery } = req.body;

    if (!personalityId || !contentType || !topic) {
      res.status(400).json({
        error: "Missing required fields: personalityId, contentType, topic",
      });
      return;
    }

    try {
      const result = await svc.preview({ personalityId, contentType, topic, contextQuery });
      res.json(result);
    } catch (err) {
      logger.error({ err }, "Content preview error");
      res.status(500).json({ error: String(err) });
    }
  });

  // ---- POST /api/content/generate ----

  router.post("/generate", requireContentKey, async (req, res) => {
    const { personalityId, contentType, topic, contextQuery } = req.body;

    if (!personalityId || !contentType || !topic) {
      res.status(400).json({
        error: "Missing required fields: personalityId, contentType, topic",
      });
      return;
    }

    try {
      const result = await svc.generate({ personalityId, contentType, topic, contextQuery });
      res.json(result);
    } catch (err) {
      logger.error({ err }, "Content generation error");
      res.status(500).json({ error: String(err) });
    }
  });

  // ---- GET /api/content/queue ----

  router.get("/queue", requireContentKey, async (req, res) => {
    const status = req.query.status as string | undefined;
    const platform = req.query.platform as string | undefined;
    const limit = Math.min(
      Math.max(1, parseInt(req.query.limit as string ?? "50", 10) || 50),
      200,
    );
    const offset = Math.max(0, parseInt(req.query.offset as string ?? "0", 10) || 0);

    try {
      const items = await svc.listQueue({ status, platform, limit, offset });
      res.json({ items, count: items.length, limit, offset });
    } catch (err) {
      logger.error({ err }, "Content queue list error");
      res.status(500).json({ error: "Failed to list content queue" });
    }
  });

  // ---- PATCH /api/content/queue/:id/review ----

  router.patch("/queue/:id/review", requireContentKey, async (req, res) => {
    const id = req.params.id as string;
    const reviewStatus = req.body.reviewStatus as string;
    const reviewComment = req.body.reviewComment as string | undefined;

    if (!reviewStatus) {
      res.status(400).json({ error: "Missing required field: reviewStatus" });
      return;
    }

    try {
      await svc.reviewItem(id, reviewStatus, reviewComment);
      res.json({ success: true, id, reviewStatus });
    } catch (err) {
      logger.error({ err, id }, "Content review error");
      const message = err instanceof Error ? err.message : String(err);
      const status = message.includes("not found") ? 404 : 400;
      res.status(status).json({ error: message });
    }
  });

  // ---- POST /api/content/queue/:id/republish/:target ----
  // Admin-only retry for a single publish-target leg (cd | sn | tokns-app).
  // Used by the content-review UI when a target failed. Rebuilds the BlogPost
  // from the stored content + topic + slug, calls the single-target publisher,
  // updates content_items.publish_results. Never overwrites a successful leg.

  router.post("/queue/:id/republish/:target", requireContentKey, async (req, res) => {
    const id = req.params.id as string;
    const target = req.params.target as "cd" | "sn" | "tokns-app";
    if (target !== "cd" && target !== "sn" && target !== "tokns-app") {
      res.status(400).json({ error: "target must be cd | sn | tokns-app" });
      return;
    }

    try {
      const rows = await db
        .select()
        .from(contentItems)
        .where(eq(contentItems.id, id))
        .limit(1);
      const item = rows[0];
      if (!item) {
        res.status(404).json({ error: "content item not found" });
        return;
      }
      if (item.contentType !== "blog_post" && item.contentType !== "slideshow_blog") {
        res.status(400).json({ error: "only blog_post / slideshow_blog items can be republished" });
        return;
      }

      // Rebuild BlogPost using the stored slug when present so we hit the same URL.
      const category = "ecosystem" as BlogPost["category"];
      const post = buildBlogPostFromContent(item.content, item.topic, category);
      if (item.slug) post.slug = item.slug;

      const { success, error, result } = await republishTarget(post, target);

      const targetKey = target === "tokns-app" ? "toknsApp" : target;
      const existingResults = item.publishResults ?? {};
      const priorLeg = existingResults[targetKey];

      // Preserve a previously-successful leg when the retry itself fails. A
      // post that was live yesterday and returns 409 ("unique constraint")
      // today still IS live — the 409 means it's already there. Recording the
      // retry failure would mask that. We keep the old success state and
      // surface the retry error separately to the caller only.
      const mergedLeg = !success && priorLeg?.success ? priorLeg : result;
      const nextResults = { ...existingResults, [targetKey]: mergedLeg };

      // If this was the first successful leg for a draft item, flip status.
      const wasDraft = item.status !== "published";
      const nowPublished = success && wasDraft;

      await db
        .update(contentItems)
        .set({
          publishResults: nextResults,
          slug: post.slug,
          updatedAt: new Date(),
          ...(nowPublished ? { status: "published", publishedAt: new Date() } : {}),
        })
        .where(eq(contentItems.id, id));

      logger.info({ id, target, success, error, slug: post.slug }, "republish leg complete");
      res.json({ success, error, target, slug: post.slug, publishResults: nextResults });
    } catch (err) {
      logger.error({ err, id, target }, "republish leg error");
      res.status(500).json({ error: err instanceof Error ? err.message : String(err) });
    }
  });

  // ---- DELETE /api/content/queue/:id ----

  router.delete("/queue/:id", requireContentKey, async (req, res) => {
    const id = req.params.id as string;
    const hard = req.query.hard === "true";

    try {
      if (hard) {
        await db.execute(sql`DELETE FROM content_items WHERE id = ${id}`);
      } else {
        await db.execute(sql`UPDATE content_items SET status = 'deleted', updated_at = NOW() WHERE id = ${id}`);
      }
      res.json({ success: true, id, action: hard ? "deleted" : "soft_deleted" });
    } catch (err) {
      logger.error({ err, id }, "Content delete error");
      res.status(500).json({ error: "Delete failed" });
    }
  });

  // ---- GET /api/content/queue/stats ----

  router.get("/queue/stats", requireContentKey, async (_req, res) => {
    try {
      const result = await svc.stats();
      res.json(result);
    } catch (err) {
      logger.error({ err }, "Content stats error");
      res.status(500).json({ error: "Stats unavailable" });
    }
  });

  // ---- POST /api/content/:id/feedback ----

  router.post("/:id/feedback", requireContentKey, async (req, res) => {
    const contentItemId = req.params.id as string;
    const { rating, comment, contentType } = req.body as {
      rating: string;
      comment?: string;
      contentType?: string;
    };

    if (!rating || (rating !== "like" && rating !== "dislike")) {
      res.status(400).json({ error: 'Missing or invalid rating. Must be "like" or "dislike"' });
      return;
    }

    const companyId = process.env.TEAM_DASHBOARD_COMPANY_ID || "8365d8c2-ea73-4c04-af78-a7db3ee7ecd4";

    try {
      const feedback = await feedbackSvc.add({
        companyId,
        contentItemId,
        contentType: (contentType as "text" | "visual") || "text",
        rating: rating as "like" | "dislike",
        comment,
        createdByUserId: req.actor?.type === "board" ? req.actor.userId ?? undefined : undefined,
      });

      // Feedback loop: propagate rating signal to intel quality layer
      // This downranks/upranks the source company's intel for future content generation
      try {
        const [item] = await db.execute(sql`
          SELECT topic FROM content_items WHERE id = ${contentItemId} LIMIT 1
        `) as unknown as Array<{ topic: string }>;
        if (item?.topic) {
          const slug = item.topic.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").slice(0, 50);
          if (rating === "dislike") {
            recordNegativeFeedback(slug);
          } else {
            recordPositiveFeedback(slug);
          }
        }
      } catch {
        // Non-critical — don't fail the feedback response
      }

      res.json(feedback);
    } catch (err) {
      logger.error({ err, contentItemId }, "Content feedback error");
      res.status(500).json({ error: "Failed to submit feedback" });
    }
  });

  // ---- GET /api/content/:id/feedback ----

  router.get("/:id/feedback", requireContentKey, async (req, res) => {
    const contentItemId = req.params.id as string;

    try {
      const feedback = await feedbackSvc.getForItem(contentItemId);
      res.json({ feedback });
    } catch (err) {
      logger.error({ err, contentItemId }, "Content feedback list error");
      res.status(500).json({ error: "Failed to fetch feedback" });
    }
  });

  // ---- GET /api/content/feedback/stats ----

  router.get("/feedback/stats", requireContentKey, async (_req, res) => {
    const companyId = process.env.TEAM_DASHBOARD_COMPANY_ID || "8365d8c2-ea73-4c04-af78-a7db3ee7ecd4";

    try {
      const stats = await feedbackSvc.getStats(companyId);
      res.json(stats);
    } catch (err) {
      logger.error({ err }, "Content feedback stats error");
      res.status(500).json({ error: "Failed to fetch feedback stats" });
    }
  });

  // ---- POST /api/content/:id/track — performance tracking (no auth) ----

  router.post("/:id/track", async (req, res) => {
    const contentItemId = req.params.id as string;
    const {
      type,
      companyId,
      utmSource,
      utmMedium,
      utmCampaign,
      origin,
    } = req.body as {
      type?: string;
      companyId?: string;
      utmSource?: string;
      utmMedium?: string;
      utmCampaign?: string;
      origin?: string;
    };

    if (!type || !["view", "click", "share"].includes(type)) {
      res.status(400).json({ error: "type must be view, click, or share" });
      return;
    }

    try {
      const scoreInc = type === "share" ? 3 : type === "click" ? 2 : 1;
      await db.execute(sql`
        UPDATE content_items
        SET click_count = click_count + 1,
            engagement_score = engagement_score + ${scoreInc}
        WHERE id = ${contentItemId}
      `);

      // Record full event row for analytics
      const ip = req.ip || "unknown";
      const ipHash = createHash("sha256").update(ip).digest("hex").slice(0, 16);
      const ua = (req.headers["user-agent"] as string) || null;
      const referrer =
        (req.headers.referer as string) ||
        (req.headers.referrer as string) ||
        null;
      const visitorType = detectVisitorType(ua ?? undefined);

      await db.insert(contentClicks).values({
        contentItemId,
        companyId: companyId ?? null,
        eventType: type,
        referrer,
        userAgent: ua,
        ipHash,
        clickOrigin: origin ?? "cd",
        visitorType,
        utmSource: utmSource ?? null,
        utmMedium: utmMedium ?? null,
        utmCampaign: utmCampaign ?? null,
      });

      res.json({ ok: true });
    } catch (err) {
      logger.warn({ err, contentItemId }, "Content tracking error");
      res.status(500).json({ error: "Tracking failed" });
    }
  });

  // ---- GET /api/content/clicks — paginated event log (auth required) ----

  router.get("/clicks", requireContentKey, async (req, res) => {
    const limit = Math.min(Number(req.query.limit) || 50, 200);
    const offset = Number(req.query.offset) || 0;
    const filterContentId = req.query.contentItemId as string | undefined;
    const filterCompanyId = req.query.companyId as string | undefined;

    try {
      const rows = await db
        .select()
        .from(contentClicks)
        .where(
          filterContentId
            ? eq(contentClicks.contentItemId, filterContentId)
            : filterCompanyId
            ? eq(contentClicks.companyId, filterCompanyId)
            : undefined,
        )
        .orderBy(desc(contentClicks.clickedAt))
        .limit(limit)
        .offset(offset);

      const [{ total }] = await db
        .select({ total: count() })
        .from(contentClicks)
        .where(
          filterContentId
            ? eq(contentClicks.contentItemId, filterContentId)
            : filterCompanyId
            ? eq(contentClicks.companyId, filterCompanyId)
            : undefined,
        );

      res.json({ rows, total });
    } catch (err) {
      logger.error({ err }, "Content clicks list error");
      res.status(500).json({ error: "Failed to fetch clicks" });
    }
  });

  // ---- GET /api/content/clicks/metrics — aggregated analytics (auth required) ----

  router.get("/clicks/metrics", requireContentKey, async (req, res) => {
    const filterCompanyId = req.query.companyId as string | undefined;
    const whereClause = filterCompanyId
      ? sql`WHERE company_id = ${filterCompanyId}`
      : sql``;
    const whereAnd = filterCompanyId
      ? sql`AND company_id = ${filterCompanyId}`
      : sql``;

    try {
      type Row = Record<string, unknown>;
      const totalResult = await db.execute<Row>(
        sql`SELECT COUNT(*)::text AS total FROM content_clicks ${whereClause}`,
      );
      const byTypeResult = await db.execute<Row>(
        sql`SELECT event_type, COUNT(*)::text AS cnt FROM content_clicks ${whereClause} GROUP BY event_type`,
      );
      const byDayResult = await db.execute<Row>(sql`
        SELECT DATE_TRUNC('day', clicked_at)::date::text AS date, COUNT(*)::text AS cnt
        FROM content_clicks
        WHERE clicked_at >= NOW() - INTERVAL '30 days' ${whereAnd}
        GROUP BY 1
        ORDER BY 1
      `);
      const byOriginResult = await db.execute<Row>(
        sql`SELECT click_origin, COUNT(*)::text AS cnt FROM content_clicks ${whereClause} GROUP BY click_origin`,
      );
      const byVisitorResult = await db.execute<Row>(
        sql`SELECT visitor_type, COUNT(*)::text AS cnt FROM content_clicks ${whereClause} GROUP BY visitor_type`,
      );

      const totalRow = (totalResult as unknown as Row[])[0] ?? {};
      res.json({
        total: Number((totalRow as { total?: string }).total ?? 0),
        byType: (byTypeResult as unknown as Row[]).map((r) => ({
          eventType: r.event_type as string,
          count: Number(r.cnt),
        })),
        byDay: (byDayResult as unknown as Row[]).map((r) => ({
          date: r.date as string,
          count: Number(r.cnt),
        })),
        byOrigin: (byOriginResult as unknown as Row[]).map((r) => ({
          origin: r.click_origin as string,
          count: Number(r.cnt),
        })),
        byVisitorType: (byVisitorResult as unknown as Row[]).map((r) => ({
          visitorType: r.visitor_type as string,
          count: Number(r.cnt),
        })),
      });
    } catch (err) {
      logger.error({ err }, "Content clicks metrics error");
      res.status(500).json({ error: "Failed to fetch metrics" });
    }
  });

  return router;
}

// ---------------------------------------------------------------------------
// Bot/agent user-agent detection (mirrors partner-go.ts)
// ---------------------------------------------------------------------------

const AGENT_UA_PATTERNS = [
  /googlebot/i, /bingbot/i, /yandexbot/i, /baiduspider/i,
  /gptbot/i, /claudebot/i, /chatgpt/i, /anthropic/i,
  /perplexity/i, /cohere/i, /ai2bot/i, /ccbot/i,
  /bytespider/i, /applebot/i, /facebookexternalhit/i,
  /twitterbot/i, /slackbot/i, /discordbot/i,
  /semrushbot/i, /ahrefsbot/i, /mj12bot/i,
  /duckduckbot/i, /ia_archiver/i, /petalbot/i,
];

function detectVisitorType(ua: string | undefined): string {
  if (!ua) return "unknown";
  for (const pattern of AGENT_UA_PATTERNS) {
    if (pattern.test(ua)) return "agent";
  }
  return "human";
}
