import type { LearnGuide } from "./types";

export const BUNDLE_GUIDES: LearnGuide[] = [
  {
    slug: "aeo-starter",
    section: "bundle",
    title: "AEO Starter — $199/mo",
    subtitle: "Three products, one invoice, one email a month.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["creditscore", "directory-listings", "partner-network", "aeo-growth"],
    steps: [
      {
        number: 1,
        eyebrow: "What's inside",
        headline: "Three products. Bundled.",
        kicker: "CreditScore Starter + Directory Featured + Partner Proof. Save 33%.",
        emphasis: "Save 33%",
        visual: {
          kind: "stack-rows",
          heading: "Inside the bundle",
          rows: [
            { primary: "CreditScore Starter", secondary: "$49/mo standalone" },
            { primary: "Directory Featured", secondary: "$199/mo standalone" },
            { primary: "Partner Proof", secondary: "$49/mo standalone" },
            { primary: "= Bundle price", secondary: "$199/mo — save $98" },
          ],
        },
        analogy: { text: "Like a combo meal. Three items on one plate, one price." },
      },
      {
        number: 2,
        eyebrow: "Who it's for",
        headline: "The curious owner.",
        kicker: "Heard of ChatGPT. Feels the shift. Doesn't know where to start.",
        emphasis: "Where to start",
        visual: {
          kind: "big-statement",
          primary: "\"I know I should — but where do I start?\"",
          secondary: "This is the bundle for that owner.",
        },
        analogy: { text: "Like a beginner gym pass. They know they should work out. They don't know which machine to use first." },
      },
      {
        number: 3,
        eyebrow: "Hands-off factor",
        headline: "One digest a month.",
        kicker: "Approve month one. Three bullets. Done.",
        emphasis: "Done",
        visual: {
          kind: "mock-frame",
          frame: "email",
          title: "Your AEO Starter monthly digest — April",
          lines: [
            "Your CreditScore moved from 68 to 74 (↑6).",
            "Directory listing refreshed — now cited 12 times this month.",
            "Partner mention placed on AustinBusinessWatch.com.",
            "All three running. No action needed.",
          ],
        },
        analogy: { text: "Like a monthly bill. Shows up, tells you what happened, you move on." },
      },
      {
        number: 4,
        eyebrow: "We do the work",
        headline: "Every month, in the background.",
        kicker: "Scans. Rewrites. Mentions. Reporting. Consolidated.",
        emphasis: "One email",
        visual: {
          kind: "stack-rows",
          heading: "What runs for them",
          rows: [
            { primary: "Site rescans", secondary: "every 6h" },
            { primary: "Directory refresh", secondary: "monthly" },
            { primary: "Partner mention placed", secondary: "monthly" },
            { primary: "One consolidated report", secondary: "monthly" },
          ],
        },
        analogy: { text: "Like having a housekeeper. You come home, it's clean, you don't think about the labor." },
      },
      {
        number: 5,
        eyebrow: "How to pitch",
        headline: "Lead with the outcome.",
        kicker: "Never the ingredient list.",
        emphasis: "the outcome",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"For $199 a month, your business shows up in AI answers, gets mentioned monthly on other sites, and gets watched automatically. You get one email. That's the whole relationship.\"",
        },
        analogy: { text: "Like selling a gym membership. Don't describe the treadmills — sell the feeling of being in shape." },
        callout: {
          kind: "tip",
          text: "Only describe the three products if they ask. Lead with what happens, not what's inside.",
        },
      },
      {
        number: 6,
        eyebrow: "Know when not to",
        headline: "Don't force it.",
        kicker: "Tight budget? Drop to $49 CreditScore. Bigger? Skip to Growth.",
        emphasis: "Skip to Growth",
        visual: {
          kind: "vs-split",
          left: { label: "Budget tight", body: "Start with CreditScore Starter at $49/mo. Upgrade later." },
          right: { label: "Bigger operation", body: "Skip Starter. Go straight to AEO Growth at $499/mo." },
        },
        analogy: { text: "Like ordering a combo. Sometimes you just want the sandwich. Sometimes the value meal is the wrong fit either direction." },
      },
    ],
  },
  {
    slug: "aeo-growth",
    section: "bundle",
    title: "AEO Growth — $499/mo",
    subtitle: "For owners past curiosity, ready for volume.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["aeo-starter", "aeo-scale", "creditscore"],
    steps: [
      {
        number: 1,
        eyebrow: "What's inside",
        headline: "Mid-tier across the board.",
        kicker: "CreditScore Pro + Directory Verified + Partner Performance. Save 37%.",
        emphasis: "Save 37%",
        visual: {
          kind: "stack-rows",
          heading: "Inside the bundle",
          rows: [
            { primary: "CreditScore Pro", secondary: "$149/mo standalone" },
            { primary: "Directory Verified", secondary: "$499/mo standalone" },
            { primary: "Partner Performance", secondary: "$149/mo standalone" },
            { primary: "= Bundle price", secondary: "$499/mo — save $298" },
          ],
        },
        analogy: { text: "Like upgrading from economy to business class. Same trip, more room, better service." },
      },
      {
        number: 2,
        eyebrow: "Who it's for",
        headline: "One lead pays for it 10×.",
        kicker: "Service businesses where a customer is worth thousands.",
        emphasis: "thousands",
        visual: {
          kind: "big-statement",
          primary: "One customer = $5,000+",
          secondary: "Lawyers. HVAC. Contractors. Dentists. The math justifies itself.",
        },
        analogy: { text: "Like an insurance policy. One claim pays for decades of premiums." },
      },
      {
        number: 3,
        eyebrow: "vs Starter",
        headline: "More work. Same hands-off.",
        kicker: "Competitor tracking. Verification. 3× mentions.",
        emphasis: "3× mentions",
        visual: {
          kind: "vs-split",
          left: { label: "AEO Starter", body: "Scans. One mention/mo. Featured listing." },
          right: { label: "AEO Growth", body: "+ Competitor tracking. + Verification. + 3 mentions/mo." },
        },
        analogy: { text: "Like going from basic to premium cable. Same show. More channels. Fewer commercials." },
      },
      {
        number: 4,
        eyebrow: "Hands-off factor",
        headline: "Work scales. Their time doesn't.",
        kicker: "More running in the background. Still one digest.",
        emphasis: "Still one digest",
        visual: {
          kind: "big-statement",
          primary: "3× the work. Same 2 minutes.",
          secondary: "They still just read the monthly email. Everything else is us.",
        },
        analogy: { text: "Like the scooter vs the motorcycle. You still just steer. The engine doing more work doesn't make you tired." },
      },
      {
        number: 5,
        eyebrow: "How to pitch",
        headline: "Against one lost lead.",
        kicker: "\"What's one customer worth? This pays for itself ten times.\"",
        emphasis: "ten times",
        visual: {
          kind: "emphasis-card",
          label: "The line",
          text: "This is $499 a month. What's one customer worth to you? If this brings you one new client a quarter, it's paid for itself ten times over.",
        },
        analogy: { text: "A question that answers itself. The owner does the math in their head — which is why you let them." },
      },
      {
        number: 6,
        eyebrow: "Upgrade path",
        headline: "Common step up from Starter.",
        kicker: "After 3-6 months, the monthly report sells Growth for you.",
        emphasis: "for you",
        visual: {
          kind: "trend-spark",
          points: [52, 55, 58, 60, 63, 65, 68, 70],
          label: "Starter → Growth upgrade window",
        },
        analogy: { text: "Like 3 months of gym progress. The visible gains sell the next level of membership — you just have to show up." },
      },
    ],
  },
  {
    slug: "aeo-scale",
    section: "bundle",
    title: "AEO Scale — $1,299/mo",
    subtitle: "Everything at premium tier. Plus the Intel API.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["aeo-growth", "all-inclusive", "intel-api"],
    steps: [
      {
        number: 1,
        eyebrow: "What's inside",
        headline: "Max tier + the data pipe.",
        kicker: "CreditScore Pro + Directory Boosted + Partner Premium + Intel Pro.",
        emphasis: "Intel Pro",
        visual: {
          kind: "stack-rows",
          heading: "Inside the bundle",
          rows: [
            { primary: "CreditScore Pro", secondary: "max tier" },
            { primary: "Directory Boosted", secondary: "top placement" },
            { primary: "Partner Premium", secondary: "editorial features" },
            { primary: "Intel API Pro", secondary: "data access" },
          ],
        },
        analogy: { text: "Like business class + the airport lounge + concierge. Everything at the top, plus the backstage access." },
      },
      {
        number: 2,
        eyebrow: "Who it's for",
        headline: "Revenue on the line.",
        kicker: "Agencies. Multi-location. Anyone with a marketing director.",
        emphasis: "marketing director",
        visual: {
          kind: "big-statement",
          primary: "Real revenue on AI answers.",
          secondary: "If a customer matters enough to measure — Scale makes the measurement.",
        },
        analogy: { text: "Like hiring a fractional CMO. You need numbers to justify the spend — Scale gives you the numbers." },
      },
      {
        number: 3,
        eyebrow: "The Intel API piece",
        headline: "Turns us into infrastructure.",
        kicker: "Their team pulls our data into their tools.",
        emphasis: "infrastructure",
        visual: {
          kind: "json-block",
          code: `// Their dashboard pulls from our API
fetch("/intel/score?business=client-name")
  .then(r => r.json())
  .then(d => render(d));
// And just keeps flowing, forever.`,
        },
        analogy: { text: "Like Stripe for data. Once it's plugged in, we become infrastructure — not a vendor." },
      },
      {
        number: 4,
        eyebrow: "Hands-off factor",
        headline: "Bigger surface. Same effort.",
        kicker: "More work running. Owner does nothing new.",
        emphasis: "nothing new",
        visual: {
          kind: "big-statement",
          primary: "4 products. 2 minutes.",
          secondary: "Everything scales up except their calendar.",
        },
        analogy: { text: "Like upgrading from econ to first class. More comfort, more service — same flight." },
      },
      {
        number: 5,
        eyebrow: "How to pitch",
        headline: "Numbers and data.",
        kicker: "Open a laptop. Real Scale report. Product sells itself.",
        emphasis: "itself",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"Here's a real Scale client's monthly report. Score trend, competitor table, citation count, citation URL list. Your team gets all of this, plus API access if you want it in your own dashboard.\"",
        },
        analogy: { text: "Like a medical scan. You don't describe the image — you let them look at it and ask questions." },
        callout: {
          kind: "tip",
          text: "If technical questions outpace you — bring Sage in. Clean handoff beats a fumble.",
        },
      },
      {
        number: 6,
        eyebrow: "When to go bigger",
        headline: "Pivot to All-Inclusive.",
        kicker: "If they ask about dedicated help — that's the move.",
        emphasis: "dedicated help",
        visual: { kind: "sage-card", blurb: "Ask for dedicated help? That's the All-Inclusive signal." },
        analogy: { text: "Like the maitre d' noticing you're a regular. When the service expectation changes, the package should too." },
      },
    ],
  },
  {
    slug: "all-inclusive",
    section: "bundle",
    title: "All-Inclusive — $2,499/mo annual",
    subtitle: "Max tier of everything. Plus Sage.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["aeo-scale", "intel-api"],
    steps: [
      {
        number: 1,
        eyebrow: "What's inside",
        headline: "Everything. Max tier.",
        kicker: "All four products at the top. Priority crons. Custom reporting.",
        emphasis: "at the top",
        visual: {
          kind: "stack-rows",
          heading: "Everything, uncapped",
          rows: [
            { primary: "CreditScore Pro", secondary: "priority" },
            { primary: "Directory Boosted", secondary: "top placement" },
            { primary: "Partner Premium", secondary: "editorial" },
            { primary: "Intel API Scale", secondary: "unlimited" },
            { primary: "Sage, your account manager", secondary: "dedicated" },
          ],
        },
        analogy: { text: "Like the all-you-can-eat prix fixe. One price, no guessing, everything on the menu." },
      },
      {
        number: 2,
        eyebrow: "The hero isn't a product",
        headline: "The hero is Sage.",
        kicker: "A real human. Dedicated. Handles everything.",
        emphasis: "Sage",
        visual: { kind: "sage-card" },
        analogy: { text: "Like hiring an executive assistant instead of buying another tool. The person IS the product." },
        callout: {
          kind: "tip",
          text: "Say her name. Not \"an account manager.\" Sage. The relationship gets real before signup.",
        },
      },
      {
        number: 3,
        eyebrow: "Who it's for",
        headline: "Executive-level hands-off.",
        kicker: "Franchises. Enterprises. \"Fix this forever\" buyers.",
        emphasis: "forever",
        visual: {
          kind: "big-statement",
          primary: "\"Just fix this forever.\"",
          secondary: "That's the owner this is for.",
        },
        analogy: { text: "Like having a chauffeur. You don't drive, you don't navigate — you arrive." },
      },
      {
        number: 4,
        eyebrow: "The pitch line",
        headline: "\"You'll talk to Sage.\"",
        kicker: "Say it early. That's the product.",
        emphasis: "the product",
        visual: {
          kind: "emphasis-card",
          label: "Say this early",
          text: "After signup, you barely hear from me. You work with Sage. She handles everything.",
        },
        analogy: { text: "A full sentence worth of product. The less you say after that, the better." },
      },
      {
        number: 5,
        eyebrow: "Annual billing",
        headline: "Know the math.",
        kicker: "$2,499 × 12 = $29,988/yr. Lump commission, then recurring.",
        emphasis: "$29,988/yr",
        visual: {
          kind: "big-statement",
          primary: "$29,988/yr",
          secondary: "One check per year. Commission pays lump on signup, then recurs on renewal.",
        },
        analogy: { text: "Like a country club membership. One annual check. Access all year." },
      },
      {
        number: 6,
        eyebrow: "Closing move",
        headline: "Warm intro > cold close.",
        kicker: "Bring Sage on a 15-min call. Almost always closes.",
        emphasis: "Almost always closes",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"Before you sign, let me get Sage on a 15-minute call. She's who you'll work with — you should meet her first.\"",
        },
        analogy: { text: "Like introducing the realtor at the showing. The deal closes on the handshake, not the listing." },
      },
    ],
  },
];
