import type { LearnGuide } from "./types";

export const FOUNDATIONS_GUIDES: LearnGuide[] = [
  {
    slug: "aeo-vs-seo",
    section: "foundations",
    title: "AEO vs SEO, explained like you're talking to your uncle",
    subtitle: "Your customers stopped Googling. They started asking.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["reading-the-room", "discovery-flow", "creditscore"],
    steps: [
      {
        number: 1,
        eyebrow: "The old way",
        headline: "You Googled. You scrolled. You clicked.",
        kicker: "Ten blue links. That was SEO.",
        emphasis: "That was SEO",
        visual: { kind: "google-serp", query: "best plumber near me" },
        analogy: { text: "Like the Yellow Pages — but ranked by Google and updated every second." },
      },
      {
        number: 2,
        eyebrow: "The new way",
        headline: "Now they ask ChatGPT.",
        kicker: "One answer. One business. No scroll.",
        emphasis: "One answer",
        visual: { kind: "chatgpt-answer" },
        analogy: { text: "Like asking a well-read friend for a recommendation. They don't hand you a list — they name one business." },
      },
      {
        number: 3,
        eyebrow: "What changed",
        headline: "The game flipped. Owners don't know yet.",
        kicker: "Page 1 of Google is nice. Being the AI's answer is everything.",
        emphasis: "Being the AI's answer is everything",
        visual: {
          kind: "vs-split",
          left: { label: "Old game", body: "Get to page 1. Compete with 9 others." },
          right: { label: "New game", body: "Be the answer. There is no second place." },
        },
        analogy: { text: "Like when radio lost listeners to streaming. Same audience, different place to show up." },
        callout: {
          kind: "watch-out",
          text: "Don't say \"LLM\" or \"generative AI.\" Say \"ChatGPT.\" Owners know what that is.",
        },
      },
      {
        number: 4,
        eyebrow: "What AEO means",
        headline: "Answer Engine Optimization.",
        kicker: "SEO for AIs. Different index. Different game.",
        emphasis: "Different game",
        visual: {
          kind: "big-statement",
          primary: "AEO",
          secondary: "Answer Engine Optimization — the craft of being the one business an AI names.",
        },
        analogy: { text: "SEO is for web pages. AEO is for answers. Same letters, different sport." },
      },
      {
        number: 5,
        eyebrow: "Why now",
        headline: "Competitors aren't playing this yet.",
        kicker: "Owners you pitch this week can lead their industry by September.",
        emphasis: "lead their industry",
        visual: {
          kind: "trend-spark",
          points: [10, 12, 14, 18, 24, 32, 43, 55, 68, 80],
          label: "AI search adoption",
        },
        analogy: { text: "Like grabbing a domain name in 1996. The ones who moved early kept the addresses everyone else wanted." },
      },
      {
        number: 6,
        eyebrow: "The one line",
        headline: "Memorize this sentence.",
        kicker: "One line, calm delivery, and you've done the hard part.",
        emphasis: "calm delivery",
        visual: {
          kind: "emphasis-card",
          label: "Memorize this",
          text: "SEO got you on Google. AEO gets you mentioned when someone asks an AI.",
        },
        analogy: { text: "Short enough to say at a doorway. Long enough to reframe their entire marketing budget." },
        callout: {
          kind: "tip",
          text: "If they go quiet, they're thinking. Don't fill the silence.",
        },
      },
    ],
  },
  {
    slug: "reading-the-room",
    section: "foundations",
    title: "Reading the room — relationship vs transactional",
    subtitle: "Not every owner wants the same pitch. Read them in two minutes.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["discovery-flow", "aeo-vs-seo", "we-already-have-seo"],
    steps: [
      {
        number: 1,
        eyebrow: "The spectrum",
        headline: "Two kinds of owners.",
        kicker: "Some buy on trust. Some buy on numbers.",
        emphasis: "trust",
        visual: {
          kind: "spectrum-bar",
          left: "Trust-led",
          right: "Numbers-led",
          position: "center",
        },
        analogy: { text: "Like asking someone on a date vs. negotiating salary. Different muscles. Different tone." },
      },
      {
        number: 2,
        eyebrow: "Relationship tells",
        headline: "They asked about YOU first.",
        kicker: "Family photos. Community. \"My customers\" said like names.",
        emphasis: "asked about YOU first",
        visual: {
          kind: "stack-rows",
          heading: "Tells to watch for",
          rows: [
            { primary: "Family photos on the wall", secondary: "sign #1" },
            { primary: "Mentions church, neighborhood, community", secondary: "sign #2" },
            { primary: "Talks about customers by name", secondary: "sign #3" },
            { primary: "Offers coffee before business", secondary: "sign #4" },
          ],
        },
        analogy: { text: "The kind of person who asks about your kids before the meeting starts." },
        callout: {
          kind: "example",
          text: "\"My dad started this shop in '87. We know everybody on the block.\" — relationship-led.",
        },
      },
      {
        number: 3,
        eyebrow: "Transactional tells",
        headline: "They looked at their watch.",
        kicker: "Asked price before purpose. Framed MBA. Interrupts.",
        emphasis: "price before purpose",
        visual: {
          kind: "stack-rows",
          heading: "Tells to watch for",
          rows: [
            { primary: "Framed credentials on the wall", secondary: "sign #1" },
            { primary: "Asked \"what does it cost\" first", secondary: "sign #2" },
            { primary: "References metrics by name", secondary: "sign #3" },
            { primary: "Checks phone while you talk", secondary: "sign #4" },
          ],
        },
        analogy: { text: "The kind of person who answers email during your pitch — not rude, just busy." },
        callout: {
          kind: "example",
          text: "\"Cut to it — what's the CAC and retention curve?\" — transactional.",
        },
      },
      {
        number: 4,
        eyebrow: "Pitch relationship-led",
        headline: "Slow down. Ask their story.",
        kicker: "Lead with hands-off. They're buying peace of mind.",
        emphasis: "peace of mind",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"I know you're busy running the shop. This is the kind of thing that just happens in the background. You get one email a month. That's it.\"",
        },
        analogy: { text: "Like sitting on a porch. Rocking chair, not stopwatch." },
      },
      {
        number: 5,
        eyebrow: "Pitch transactional",
        headline: "Speed up. Show numbers.",
        kicker: "Open the laptop. Let the product sell.",
        emphasis: "Let the product sell",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"Here's a real client's 30-day trend. Score went from 48 to 74. Citations up 3×. That's the whole dashboard. Sign up or don't — the numbers are the numbers.\"",
        },
        analogy: { text: "Like a board meeting. Agenda, numbers, decision." },
      },
      {
        number: 6,
        eyebrow: "When in doubt",
        headline: "Start warm.",
        kicker: "Transactional won't mind. Relationship-led will.",
        emphasis: "Start warm",
        visual: {
          kind: "big-statement",
          primary: "Start warm.",
          secondary: "You can always speed up. You can't un-cool a cold opening.",
        },
        analogy: { text: "Easier to speed up a slow car than to warm up a cold one. Same with conversations." },
        callout: {
          kind: "tip",
          text: "Fastest read: \"what does it do?\" = transactional. \"who are you?\" = relationship. Decides everything.",
        },
      },
    ],
  },
  {
    slug: "discovery-flow",
    section: "foundations",
    title: "The walk-in discovery flow",
    subtitle: "Five questions to ask before you ever mention the product.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["reading-the-room", "aeo-vs-seo", "creditscore"],
    steps: [
      {
        number: 1,
        eyebrow: "Why ask first",
        headline: "Talk first: you're a salesperson.",
        kicker: "Ask first: you're a consultant. Owners buy from consultants.",
        emphasis: "consultant",
        visual: {
          kind: "big-statement",
          primary: "Ask, don't tell.",
          secondary: "The first 90 seconds decide whether you're welcome or tolerated.",
        },
        analogy: { text: "Like a doctor. They ask where it hurts before prescribing. You're doing the same." },
      },
      {
        number: 2,
        eyebrow: "Question 1",
        headline: "\"Found you through ChatGPT lately?\"",
        kicker: "No jargon. Opens the conversation either way.",
        emphasis: "either way",
        visual: {
          kind: "question-card",
          number: 1,
          question: "\"Have any customers mentioned finding you through ChatGPT lately?\"",
        },
        analogy: { text: "Like asking if anyone at the barbershop mentioned your sign. Gauges awareness without selling." },
      },
      {
        number: 3,
        eyebrow: "Question 2",
        headline: "\"Know what ChatGPT says about you?\"",
        kicker: "Almost nobody does. Show them — on your phone, right there.",
        emphasis: "Show them",
        visual: {
          kind: "question-card",
          number: 2,
          question: "\"Do you know what shows up when I ask ChatGPT 'best [your category] in [your city]'?\"",
        },
        analogy: { text: "Like handing someone a mirror. The surprise is the pitch." },
        callout: {
          kind: "tip",
          text: "Pull this up BEFORE the meeting. Nothing kills momentum like a slow phone.",
        },
      },
      {
        number: 4,
        eyebrow: "Question 3",
        headline: "\"Who handles the website now?\"",
        kicker: "Not replacing. Coexisting. Write the name down.",
        emphasis: "Coexisting",
        visual: {
          kind: "question-card",
          number: 3,
          question: "\"Who handles your website and digital stuff right now?\"",
        },
        analogy: { text: "Like asking who their accountant is before suggesting a new tax strategy. Respect the existing player." },
      },
      {
        number: 5,
        eyebrow: "Question 4",
        headline: "\"Monthly marketing budget, roughly?\"",
        kicker: "Not to quote against. To fit the right offer.",
        emphasis: "fit the right offer",
        visual: {
          kind: "question-card",
          number: 4,
          question: "\"What's roughly the monthly budget for all of that?\"",
        },
        analogy: { text: "Like a tailor measuring before suggesting a suit. You can't fit what you haven't measured." },
      },
      {
        number: 6,
        eyebrow: "Question 5",
        headline: "\"Want a free scan of your site?\"",
        kicker: "60 seconds. No signup. Leaves them with a real report.",
        emphasis: "real report",
        visual: {
          kind: "question-card",
          number: 5,
          question: "\"Want me to pull up a free scan of your site real quick?\"",
        },
        analogy: { text: "Like a free oil check at the auto shop. The service is the hook — but it's a real service." },
      },
    ],
  },
];
