import type { LearnGuide } from "./types";

export const OBJECTION_GUIDES: LearnGuide[] = [
  {
    slug: "we-already-have-seo",
    section: "objections",
    title: "\"We already have SEO\"",
    subtitle: "The most common deflection. Don't fight it — reframe it.",
    readingMinutes: 1,
    videoEmbedUrl: null,
    relatedSlugs: ["aeo-vs-seo", "another-dashboard"],
    steps: [
      {
        number: 1,
        eyebrow: "What they said",
        headline: "\"We already pay for SEO.\"",
        kicker: "Or some version — \"my guy handles it.\"",
        emphasis: "my guy",
        visual: {
          kind: "bubble",
          tone: "said",
          text: "\"We already pay someone for SEO. We're covered on that.\"",
        },
        analogy: { text: "Like when someone says they already have a gym membership — it's not a no, it's a reflex." },
      },
      {
        number: 2,
        eyebrow: "What it means",
        headline: "Not a refusal. A deflection.",
        kicker: "They feel they checked the box. Fear of another line item.",
        emphasis: "A deflection",
        visual: {
          kind: "bubble",
          tone: "thought",
          text: "What they're really thinking: \"I don't want another monthly bill. I've already got one for marketing.\"",
        },
        analogy: { text: "Like 'I'm watching my diet' at a party. It's not really about the diet — it's about not wanting the conversation." },
      },
      {
        number: 3,
        eyebrow: "Respond",
        headline: "Agree first. Reframe second.",
        kicker: "\"Good — keep your SEO. I'm talking about what ChatGPT sees.\"",
        emphasis: "Different system",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"Good — SEO is important, keep paying for it. What I'm talking about is the part SEO doesn't touch: when someone asks ChatGPT for a recommendation. Different system. Want to see what yours looks like right now?\"",
        },
        analogy: { text: "Like judo. Don't push back. Use their momentum to move them somewhere new." },
        callout: {
          kind: "tip",
          text: "Never argue with their vendor. \"They're good at SEO. We do a different thing.\" Keeps pride intact.",
        },
      },
    ],
  },
  {
    slug: "another-dashboard",
    section: "objections",
    title: "\"Another dashboard I'll never open?\"",
    subtitle: "They've been burned by software that demanded their time.",
    readingMinutes: 1,
    videoEmbedUrl: null,
    relatedSlugs: ["creditscore", "how-do-i-know-it-works"],
    steps: [
      {
        number: 1,
        eyebrow: "What they said",
        headline: "\"I never log into the one I have.\"",
        kicker: "Tired-of-software talking.",
        emphasis: "Tired",
        visual: {
          kind: "bubble",
          tone: "said",
          text: "\"Is this another dashboard I'm supposed to check every day? I already have five apps I never open.\"",
        },
        analogy: { text: "Like someone who's been burned by too many free trials. The fear isn't the product — it's the obligation." },
      },
      {
        number: 2,
        eyebrow: "What it means",
        headline: "They've been burned.",
        kicker: "Sold a tool. Expected to work it. Felt dumb. Gun-shy now.",
        emphasis: "Gun-shy",
        visual: {
          kind: "bubble",
          tone: "thought",
          text: "What they're thinking: \"Someone's going to ask me in 3 months why I'm not using this, and I won't have an answer.\"",
        },
        analogy: { text: "Like the gym you paid for and didn't go to. The guilt is louder than the cost." },
      },
      {
        number: 3,
        eyebrow: "Respond",
        headline: "The product is the email.",
        kicker: "\"Honestly, same. One email a month. Dashboard exists but you'll never need it.\"",
        emphasis: "the email",
        visual: {
          kind: "mock-frame",
          frame: "email",
          title: "Your CreditScore update — April",
          lines: [
            "Your score moved from 68 to 74 this month.",
            "New citation pickup: 3 sources added.",
            "Competitor \"Austin Pro\" dropped to 52.",
            "No action needed from you.",
          ],
        },
        analogy: { text: "Like a subscription to a calm magazine. It arrives. You glance. You move on. That's the whole commitment." },
      },
    ],
  },
  {
    slug: "how-do-i-know-it-works",
    section: "objections",
    title: "\"How do I know it's working?\"",
    subtitle: "They want a number. Give them one.",
    readingMinutes: 1,
    videoEmbedUrl: null,
    relatedSlugs: ["creditscore", "directory-listings"],
    steps: [
      {
        number: 1,
        eyebrow: "What they said",
        headline: "\"How do I know this is working?\"",
        kicker: "Sometimes ROI. Sometimes \"will this work?\"",
        emphasis: "ROI",
        visual: {
          kind: "bubble",
          tone: "said",
          text: "\"How will I actually know this is working? I've been burned by marketing that promised things and delivered reports full of vague numbers.\"",
        },
        analogy: { text: "Like asking a contractor how you'll know the roof is holding — a fair, smart question." },
      },
      {
        number: 2,
        eyebrow: "What it means",
        headline: "They've been sold vague before.",
        kicker: "Glossy reports, zero traceable outcomes. Trust test.",
        emphasis: "trust test",
        visual: {
          kind: "bubble",
          tone: "thought",
          text: "What they're really asking: \"Can you show me one specific, concrete number that moves? Or is this another handwave?\"",
        },
        analogy: { text: "Like when someone asks \"but how do you really feel?\" — they're testing whether you'll answer straight." },
      },
      {
        number: 3,
        eyebrow: "Respond",
        headline: "Show specifics. Not promises.",
        kicker: "\"Here's a real trend line. Number doesn't move, you cancel.\"",
        emphasis: "you cancel",
        visual: {
          kind: "trend-spark",
          points: [48, 51, 54, 58, 62, 66, 70, 74],
          label: "Real client: 30-day score",
        },
        analogy: { text: "Like a thermometer. The number goes up or it doesn't. There's nothing to argue about." },
      },
    ],
  },
  {
    slug: "need-to-think-about-it",
    section: "objections",
    title: "\"I need to think about it\"",
    subtitle: "Don't push. Leave them with something real.",
    readingMinutes: 1,
    videoEmbedUrl: null,
    relatedSlugs: ["discovery-flow", "creditscore"],
    steps: [
      {
        number: 1,
        eyebrow: "What they said",
        headline: "\"Let me think about it.\"",
        kicker: "The graceful no.",
        emphasis: "graceful no",
        visual: {
          kind: "bubble",
          tone: "said",
          text: "\"Let me think about it. Send me some info and I'll get back to you.\"",
        },
        analogy: { text: "Like when a date says \"I'll text you.\" Could be real. Probably isn't." },
      },
      {
        number: 2,
        eyebrow: "What it means",
        headline: "One of three things.",
        kicker: "Not the decider. Doesn't trust yet. Or a polite pass.",
        emphasis: "three things",
        visual: {
          kind: "stack-rows",
          heading: "What it usually means",
          rows: [
            { primary: "Not the actual decision-maker", secondary: "40%" },
            { primary: "Doesn't trust the product yet", secondary: "35%" },
            { primary: "Polite \"no\"", secondary: "25%" },
          ],
        },
        analogy: { text: "Like a politician saying \"we're looking into it.\" Could mean anything. Usually means no." },
      },
      {
        number: 3,
        eyebrow: "Respond",
        headline: "Don't push. Run the scan.",
        kicker: "\"No commitment. Takes a minute. You'll have the report.\"",
        emphasis: "the report",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"Totally fair — no pressure. One thing before I go: let me run the free scan while I'm here. No commitment. You'll have the report either way, think it over when you want.\"",
        },
        analogy: { text: "Like giving someone a business card at the door instead of pitching again. Lower pressure, higher follow-through." },
        callout: {
          kind: "tip",
          text: "Never ask \"when can I follow up?\" — sounds desperate. Let the report do the follow-up for you.",
        },
      },
    ],
  },
  {
    slug: "nephew-handles-it",
    section: "objections",
    title: "\"My nephew handles the website\"",
    subtitle: "Never position against family. Always alongside.",
    readingMinutes: 1,
    videoEmbedUrl: null,
    relatedSlugs: ["we-already-have-seo", "another-dashboard"],
    steps: [
      {
        number: 1,
        eyebrow: "What they said",
        headline: "\"My nephew takes care of it.\"",
        kicker: "Or cousin. Or church friend. Family relationship IS the product.",
        emphasis: "the product",
        visual: {
          kind: "bubble",
          tone: "said",
          text: "\"My nephew / brother-in-law / kid has been doing our website for years. I don't want to step on that.\"",
        },
        analogy: { text: "Like suggesting someone change dentists. The tooth isn't the point — the trust is." },
      },
      {
        number: 2,
        eyebrow: "What it means",
        headline: "Don't step on family.",
        kicker: "They might know nephew isn't great. They won't fire him.",
        emphasis: "won't fire him",
        visual: {
          kind: "bubble",
          tone: "thought",
          text: "What they're thinking: \"Nephew helps at the family barbecue. I'm not firing him over a website score.\"",
        },
        analogy: { text: "Like trying to sell someone a better accountant when their cousin does their taxes. The relationship outranks the results." },
      },
      {
        number: 3,
        eyebrow: "Respond",
        headline: "Alongside, never against.",
        kicker: "\"He'll love the report. We do AI visibility. He keeps his lane.\"",
        emphasis: "alongside",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"Perfect — keep him doing the website. We don't touch that. We do the AI visibility piece. Send me his email — I'll CC him on everything so he stays in the loop.\"",
        },
        analogy: { text: "Like adding a specialist to a GP's care. The family doctor keeps the primary relationship. Nobody gets replaced." },
        callout: {
          kind: "tip",
          text: "Get the nephew's email. \"I'll CC him on everything.\" Turns a blocker into an advocate.",
        },
      },
    ],
  },
  {
    slug: "how-do-i-cancel",
    section: "objections",
    title: "\"How do I cancel?\"",
    subtitle: "It's a buy signal, not an escape plan.",
    readingMinutes: 1,
    videoEmbedUrl: null,
    relatedSlugs: ["creditscore", "aeo-starter"],
    steps: [
      {
        number: 1,
        eyebrow: "What they said",
        headline: "\"What if I want to stop?\"",
        kicker: "Or \"is there a contract?\" Due diligence.",
        emphasis: "Due diligence",
        visual: {
          kind: "bubble",
          tone: "said",
          text: "\"Wait — what if I want to cancel? Am I locked in? How does that work?\"",
        },
        analogy: { text: "Like reading the terms before signing a lease. Responsible, not rejecting." },
      },
      {
        number: 2,
        eyebrow: "What it means",
        headline: "They want it to be safe to START.",
        kicker: "Buy signal dressed as an objection.",
        emphasis: "buy signal",
        visual: {
          kind: "bubble",
          tone: "thought",
          text: "What they're really asking: \"Can I trust you enough to try this, knowing I can bail if it's not working?\"",
        },
        analogy: { text: "Like checking for the exit before sitting down at a restaurant. Finding the exit makes them more comfortable staying." },
      },
      {
        number: 3,
        eyebrow: "Respond",
        headline: "Show them the button.",
        kicker: "\"One click. No contract.\"",
        emphasis: "One click",
        visual: {
          kind: "mock-frame",
          frame: "browser",
          title: "Your subscription settings",
          lines: [
            "Current plan: CreditScore Starter — $49/mo",
            "Billing: monthly, next charge May 23",
            "[ Cancel subscription ]  ← one click, ends at period end",
            "No contract. No cancellation fee.",
          ],
        },
        analogy: { text: "Like showing the emergency exits on a plane. Counter-intuitive comfort — pointing at the escape makes people less likely to use it." },
      },
    ],
  },
];
