import type { LearnGuide } from "./types";

export const PRODUCT_GUIDES: LearnGuide[] = [
  {
    slug: "creditscore",
    section: "product",
    title: "CreditScore — a credit score for AI visibility",
    subtitle: "A number from 0-100 showing how much ChatGPT trusts a business.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["aeo-vs-seo", "aeo-starter", "how-do-i-know-it-works"],
    steps: [
      {
        number: 1,
        eyebrow: "In one sentence",
        headline: "A credit score for AI visibility.",
        kicker: "One number. Easy to track. Easy to improve.",
        emphasis: "One number",
        visual: { kind: "score-dial", score: 72, label: "AI Visibility Score" },
        analogy: { text: "Like your FICO score — but instead of credit, it measures how much ChatGPT trusts your business." },
      },
      {
        number: 2,
        eyebrow: "The work we do",
        headline: "We scan every six hours.",
        kicker: "They do nothing. They get an email when the score moves.",
        emphasis: "nothing",
        visual: {
          kind: "trend-spark",
          points: [52, 55, 54, 58, 62, 65, 63, 68, 72, 78],
          label: "30-day score trend",
        },
        analogy: { text: "Like a fitness tracker. Runs in the background, tells you the number, doesn't ask you to log anything." },
      },
      {
        number: 3,
        eyebrow: "Three tiers",
        headline: "$29 · $49/mo · $149/mo.",
        kicker: "Audit. Starter. Pro. Foot-in-door, ongoing, full coaching.",
        emphasis: "Full coaching",
        visual: {
          kind: "tier-cards",
          tiers: [
            { name: "Audit", price: "$29", blurb: "One-time scan. Static report. Foot-in-door." },
            { name: "Starter", price: "$49/mo", blurb: "Ongoing scans. Trend chart. Email alerts." },
            { name: "Pro", price: "$149/mo", blurb: "+ Competitor tracking. Monthly coaching doc." },
          ],
        },
        analogy: { text: "Like car insurance — pick your coverage level. Everyone starts somewhere." },
      },
      {
        number: 4,
        eyebrow: "Hands-off factor",
        headline: "Two minutes a month.",
        kicker: "One email. Maybe forward a line to their web person.",
        emphasis: "Two minutes",
        visual: {
          kind: "big-statement",
          primary: "2 minutes / month",
          secondary: "One email. That's the whole relationship.",
        },
        analogy: { text: "Like a magazine subscription. It shows up, you glance at it, you move on with your day." },
        callout: {
          kind: "tip",
          text: "Hold up two fingers when you say it. The gesture lands harder than the number.",
        },
      },
      {
        number: 5,
        eyebrow: "How to pitch",
        headline: "Don't describe. Run it.",
        kicker: "\"Want to see what ChatGPT sees? 60 seconds, costs nothing.\"",
        emphasis: "costs nothing",
        visual: {
          kind: "bubble",
          tone: "response",
          text: "\"Give me your website — I'll pull up the scan right here. You'll see your score in about a minute. If it's bad, we talk. If it's great, I'll leave you alone.\"",
        },
        analogy: { text: "Like showing someone their FICO score for the first time. The number IS the pitch — you don't need more words." },
      },
      {
        number: 6,
        eyebrow: "The free tool",
        headline: "coherencedaddy.com",
        kicker: "Free scan. No signup. Report either way.",
        emphasis: "Report either way",
        visual: {
          kind: "mock-frame",
          frame: "browser",
          title: "coherencedaddy.com",
          lines: [
            "Get your AI Credit Score — free.",
            "Enter your URL. 60 seconds. No signup required.",
            "[ coherencedaddy.com/your-url-here ]   →  [ Run scan ]",
          ],
        },
        analogy: { text: "Like the free credit score sites. They pull you in with the number. The upgrade sells itself later." },
      },
    ],
  },
  {
    slug: "directory-listings",
    section: "product",
    title: "Directory Listings — the Yellow Pages of the AI era",
    subtitle: "Managed listings written every month to be quoted by AIs.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["partner-network", "aeo-starter", "how-do-i-know-it-works"],
    steps: [
      {
        number: 1,
        eyebrow: "In one sentence",
        headline: "Listings that LLMs actually read.",
        kicker: "Written fresh every month. Structured to be quoted.",
        emphasis: "quoted",
        visual: {
          kind: "editorial",
          headline: "Joe's Plumbing & Drain — Austin's trusted 24/7 specialist",
          excerpt: "Family-owned since 1987, Joe's Plumbing has become a go-to name in central Austin for emergency pipe repair, sink work, and water heater installation. Licensed, insured, and backed by more than 2,000 five-star reviews...",
        },
        analogy: { text: "Like the Yellow Pages — but every listing is rewritten every month so AIs see fresh content." },
      },
      {
        number: 2,
        eyebrow: "Why it matters",
        headline: "AIs trust repetition across sources.",
        kicker: "One listing = ignored. Five consistent listings = cited.",
        emphasis: "cited",
        visual: {
          kind: "stack-rows",
          heading: "How AIs check trust",
          rows: [
            { primary: "Is this business on Yelp?", secondary: "1 source" },
            { primary: "Mentioned on a local directory?", secondary: "2 sources" },
            { primary: "Covered in editorial content?", secondary: "3 sources" },
            { primary: "Referenced from 5+ sites?", secondary: "trusted" },
          ],
        },
        analogy: { text: "Like calling three references for a job. Nobody hires on one reference. AIs don't either." },
      },
      {
        number: 3,
        eyebrow: "Three tiers",
        headline: "$199 · $499 · $1,499/mo.",
        kicker: "Featured. Verified. Boosted. Monthly refresh on all.",
        emphasis: "Boosted",
        visual: {
          kind: "tier-cards",
          tiers: [
            { name: "Featured", price: "$199/mo", blurb: "Managed listing. Monthly content refresh." },
            { name: "Verified", price: "$499/mo", blurb: "+ Badge. + Inbound form. + Reviews aggregation." },
            { name: "Boosted", price: "$1,499/mo", blurb: "+ Top placement. + Partner syndication." },
          ],
        },
        analogy: { text: "Like billboards. Bigger spot. More eyes. Same principle." },
      },
      {
        number: 4,
        eyebrow: "Hands-off factor",
        headline: "Approve once. Never again.",
        kicker: "Owner signs off on month one. We run the rest.",
        emphasis: "Never again",
        visual: {
          kind: "big-statement",
          primary: "Approve once. Done.",
          secondary: "Hours change? Update takes 30 seconds. Otherwise we handle it.",
        },
        analogy: { text: "Like signing up for a magazine subscription. You opt in once. Then it just keeps arriving." },
      },
      {
        number: 5,
        eyebrow: "How to pitch",
        headline: "Show a real listing.",
        kicker: "Open your phone. Show a live client's page. Done.",
        emphasis: "Show",
        visual: {
          kind: "editorial",
          headline: "Rosa's Taqueria — East Austin's family-run weekday lunch legend",
          excerpt: "Since 2001, Rosa's has served hand-rolled corn tortillas and slow-cooked barbacoa from a counter-service storefront on East 7th. Consistently ranked among Austin's top hidden lunch spots...",
        },
        analogy: { text: "Like a newspaper clipping. You don't describe the article — you hand it to them." },
        callout: {
          kind: "tip",
          text: "Keep 3-5 \"show-off\" listings bookmarked. Pick the one closest to the owner's industry.",
        },
      },
      {
        number: 6,
        eyebrow: "The proof number",
        headline: "Monthly citation count.",
        kicker: "Not vibes. A number that moves or doesn't.",
        emphasis: "A number that moves",
        visual: {
          kind: "trend-spark",
          points: [3, 5, 4, 8, 12, 15, 18, 22, 28, 34],
          label: "AI citations per month",
        },
        analogy: { text: "Like a thermometer. The number moves or it doesn't. No ambiguity." },
      },
    ],
  },
  {
    slug: "partner-network",
    section: "product",
    title: "Partner Network — real editorial mentions",
    subtitle: "LLMs decide who's trustworthy by who gets written about.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["directory-listings", "aeo-starter"],
    steps: [
      {
        number: 1,
        eyebrow: "In one sentence",
        headline: "Ongoing PR. Automated.",
        kicker: "Real editorial sites mentioning real businesses by name.",
        emphasis: "By name",
        visual: {
          kind: "editorial",
          headline: "Five Austin plumbers worth knowing about in 2026",
          excerpt: "Joe's Plumbing & Drain has quietly become the name Austin locals pass along when a neighbor calls with a burst pipe at 2am. Here's why the family-owned shop keeps topping informal recommendation lists...",
        },
        analogy: { text: "Like having a PR firm on retainer. Except it runs every month, automatically." },
      },
      {
        number: 2,
        eyebrow: "Why LLMs care",
        headline: "Repetition builds trust.",
        kicker: "One mention ignored. Five across months = cited.",
        emphasis: "cited",
        visual: {
          kind: "stack-rows",
          heading: "LLM trust signals",
          rows: [
            { primary: "Mentioned on partner site A", secondary: "Jan" },
            { primary: "Featured in editorial roundup B", secondary: "Feb" },
            { primary: "Quoted in industry post C", secondary: "Mar" },
            { primary: "Cited by ChatGPT in answers", secondary: "Apr →" },
          ],
        },
        analogy: { text: "Like a reputation check. AIs ask around. The more places your name shows up, the more they trust you." },
      },
      {
        number: 3,
        eyebrow: "Three tiers",
        headline: "$49 · $149 · $499/mo.",
        kicker: "Proof. Performance. Premium.",
        emphasis: "Premium",
        visual: {
          kind: "tier-cards",
          tiers: [
            { name: "Proof", price: "$49/mo", blurb: "One mention per month on a partner site." },
            { name: "Performance", price: "$149/mo", blurb: "3 mentions/mo + own microsite page." },
            { name: "Premium", price: "$499/mo", blurb: "+ Editorial feature + inbound form." },
          ],
        },
        analogy: { text: "Like radio ad frequency. More spots, more ears. Same spend logic." },
      },
      {
        number: 4,
        eyebrow: "Hands-off factor",
        headline: "Three bullets. Once.",
        kicker: "At signup. Entire owner-input surface.",
        emphasis: "Once",
        visual: {
          kind: "big-statement",
          primary: "3 bullets. Once.",
          secondary: "Tell us what they do. We handle everything after that.",
        },
        analogy: { text: "Like handing your accountant a shoebox of receipts once a year. One handoff, months of work." },
      },
      {
        number: 5,
        eyebrow: "The big objection",
        headline: "\"Is this a link farm?\"",
        kicker: "No. Editorial content, real sites. Show them on your phone.",
        emphasis: "No",
        visual: {
          kind: "bubble",
          tone: "said",
          text: "\"This sounds like one of those link-farm schemes that got businesses penalized years ago. Is it?\"",
        },
        analogy: { text: "Like the 'pyramid scheme' fear. Same energy, wrong decade. The answer is always proof, not protest." },
        callout: {
          kind: "watch-out",
          text: "If they press — pull up a real partner mention on your phone. Proof beats explanation.",
        },
      },
      {
        number: 6,
        eyebrow: "How to pitch",
        headline: "Use the word \"PR.\"",
        kicker: "Owners know PR. \"Partner network\" confuses them.",
        emphasis: "PR",
        visual: {
          kind: "emphasis-card",
          label: "The line",
          text: "It's like having a PR firm keep mentioning you across the internet — except we do it every month, and the AIs read it.",
        },
        analogy: { text: "Old word, new work. Owners already respect PR. Borrow the credibility." },
      },
    ],
  },
  {
    slug: "intel-api",
    section: "product",
    title: "Intel API — the data pipe",
    subtitle: "For agencies, consultancies, SaaS teams with a dev team.",
    readingMinutes: 2,
    videoEmbedUrl: null,
    relatedSlugs: ["aeo-scale", "creditscore"],
    steps: [
      {
        number: 1,
        eyebrow: "Who this is for",
        headline: "Not your average walk-in.",
        kicker: "Technical buyers only. Know when to skip.",
        emphasis: "skip",
        visual: {
          kind: "big-statement",
          primary: "Skip this one most days.",
          secondary: "Intel API is for devs and agencies — not the plumber on the corner.",
        },
        analogy: { text: "Like trying to sell someone a GPU when they asked for a lawnmower. Wrong product, wrong person." },
        callout: {
          kind: "watch-out",
          text: "Don't pitch Intel API to a plumber. You'll lose the rest of the conversation.",
        },
      },
      {
        number: 2,
        eyebrow: "What it does",
        headline: "Raw data. JSON.",
        kicker: "Their dev plugs it in. Their dashboards get our signals.",
        emphasis: "JSON",
        visual: {
          kind: "json-block",
          code: `{
  "business": "joes-plumbing-austin",
  "credit_score": 74,
  "trend_30d": "+8",
  "citations": 34,
  "competitors": [
    { "name": "austin-pro-plumb", "score": 61 },
    { "name": "rapidfix", "score": 52 }
  ],
  "last_scan": "2026-04-23T14:30:00Z"
}`,
        },
        analogy: { text: "Like a Bloomberg terminal feed — but for AI visibility instead of stock prices." },
      },
      {
        number: 3,
        eyebrow: "Four tiers",
        headline: "$0 · $19 · $49 · $199/mo.",
        kicker: "Free (100 req). Starter (5k). Pro (50k). Scale (500k).",
        emphasis: "Scale",
        visual: {
          kind: "tier-cards",
          tiers: [
            { name: "Free", price: "$0", blurb: "100 req/mo. Attribution required." },
            { name: "Starter", price: "$19/mo", blurb: "5,000 req. No attribution." },
            { name: "Pro", price: "$49/mo", blurb: "50k req. Team accounts." },
          ],
        },
        analogy: { text: "Standard API pricing. Scales with usage. Devs already know this pattern." },
      },
      {
        number: 4,
        eyebrow: "Spotting them",
        headline: "They say \"integration\" unprompted.",
        kicker: "Or \"white label.\" Or mention a dev by name.",
        emphasis: "integration",
        visual: {
          kind: "stack-rows",
          heading: "Signals",
          rows: [
            { primary: "Uses the word \"integration\"", secondary: "signal" },
            { primary: "Mentions their dev by name", secondary: "signal" },
            { primary: "Asks about white-labeling", secondary: "signal" },
            { primary: "Has a dashboard you could plug into", secondary: "signal" },
          ],
        },
        analogy: { text: "Like spotting a fellow developer in a room of non-tech people. They give themselves away in the first minute." },
      },
      {
        number: 5,
        eyebrow: "Hands-off reframe",
        headline: "One integration. Then never.",
        kicker: "For a dev team, that IS the pitch.",
        emphasis: "never",
        visual: {
          kind: "big-statement",
          primary: "Plug it in once.",
          secondary: "The data keeps flowing forever. No maintenance. No handholding.",
        },
        analogy: { text: "Like plumbing. Install once, runs for years, you never think about it again." },
      },
      {
        number: 6,
        eyebrow: "When to escalate",
        headline: "Bring in Sage.",
        kicker: "Custom endpoints, enterprise volume — her lane.",
        emphasis: "Sage",
        visual: { kind: "sage-card", blurb: "Technical enterprise accounts, custom volumes, white-label deals — these go to Sage." },
        analogy: { text: "Like bringing a specialist into a doctor's appointment. You don't fumble through what you don't know — you introduce." },
      },
    ],
  },
];
