/**
 * API Registry — static catalog of all route groups with metadata.
 * Used by the API Dashboard to show all endpoints and their status.
 */

export interface ApiRouteGroup {
  name: string;
  prefix: string;
  endpointCount: number;
  description: string;
  authType: "public" | "authenticated" | "content-key" | "ingest-key";
  category: "core" | "content" | "intel" | "integrations" | "public" | "system" | "plugins";
  pingUrl: string;
}

export const API_REGISTRY: ApiRouteGroup[] = [
  // ── Core ──────────────────────────────────────────────────────────────
  {
    name: "Health",
    prefix: "/api/health",
    endpointCount: 3,
    description: "Health checks, readiness probes, and system metrics",
    authType: "public",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Companies",
    prefix: "/api/companies",
    endpointCount: 16,
    description: "Company CRUD, branding, import/export, archiving",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/companies",
  },
  {
    name: "Agents",
    prefix: "/api/agents",
    endpointCount: 38,
    description: "Agent management, configuration, heartbeat, runtime state",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/agents/me",
  },
  {
    name: "Issues",
    prefix: "/api/issues",
    endpointCount: 28,
    description: "Issue tracking, comments, attachments, documents, work products",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/issues",
  },
  {
    name: "Projects",
    prefix: "/api/projects",
    endpointCount: 7,
    description: "Project management and workspaces",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/projects",
  },
  {
    name: "Goals",
    prefix: "/api/goals",
    endpointCount: 5,
    description: "Goal tracking and management",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/goals",
  },
  {
    name: "Approvals",
    prefix: "/api/approvals",
    endpointCount: 10,
    description: "Approval workflows, comments, and linked issues",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/approvals",
  },
  {
    name: "Routines",
    prefix: "/api/routines",
    endpointCount: 9,
    description: "Scheduled routines, triggers, and manual runs",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/routines",
  },
  {
    name: "Dashboard",
    prefix: "/api/dashboard",
    endpointCount: 1,
    description: "Dashboard summary data",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Activity",
    prefix: "/api/activity",
    endpointCount: 5,
    description: "Activity logging and issue run history",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Costs",
    prefix: "/api/costs",
    endpointCount: 16,
    description: "Cost tracking, budgets, finance events, window spend",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Secrets",
    prefix: "/api/secrets",
    endpointCount: 5,
    description: "Secret management and rotation",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Access & Auth",
    prefix: "/api/auth",
    endpointCount: 20,
    description: "Authentication, invites, CLI auth, member management",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/auth/get-session",
  },
  {
    name: "Assets",
    prefix: "/api/assets",
    endpointCount: 3,
    description: "Image uploads, company logos, asset content",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Company Skills",
    prefix: "/api/company-skills",
    endpointCount: 8,
    description: "Skill installation, updates, and file management",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Agent Ops",
    prefix: "/api/agent-ops",
    endpointCount: 1,
    description: "Agent operations dashboard",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Execution Workspaces",
    prefix: "/api/execution-workspaces",
    endpointCount: 3,
    description: "Execution environment management",
    authType: "authenticated",
    category: "core",
    pingUrl: "/api/health/readiness",
  },

  // ── Content ───────────────────────────────────────────────────────────
  {
    name: "Content",
    prefix: "/api/content",
    endpointCount: 9,
    description: "Text content generation, queue, review, feedback",
    authType: "content-key",
    category: "content",
    pingUrl: "/api/content/queue/stats",
  },
  {
    name: "Visual Content",
    prefix: "/api/visual",
    endpointCount: 7,
    description: "AI image/video generation, job tracking, asset serving",
    authType: "content-key",
    category: "content",
    pingUrl: "/api/visual/backends",
  },
  {
    name: "Trends & SEO",
    prefix: "/api/trends",
    endpointCount: 3,
    description: "Trend scanning (CoinGecko, HackerNews, Google Trends) and SEO blog generation",
    authType: "content-key",
    category: "content",
    pingUrl: "/api/trends/signals",
  },
  {
    name: "Media Drop",
    prefix: "/api/media",
    endpointCount: 6,
    description: "File upload and media library management",
    authType: "content-key",
    category: "content",
    pingUrl: "/api/health/readiness",
  },

  // ── Intel ─────────────────────────────────────────────────────────────
  {
    name: "Intel",
    prefix: "/api/intel",
    endpointCount: 18,
    description: "Blockchain intel — companies, prices, news, social, discovery",
    authType: "public",
    category: "intel",
    pingUrl: "/api/intel/stats",
  },

  // ── Integrations ──────────────────────────────────────────────────────
  {
    name: "X/Twitter OAuth",
    prefix: "/api/x/oauth",
    endpointCount: 6,
    description: "Twitter OAuth 2.0 PKCE flow and rate limit management",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/x/oauth/status",
  },
  {
    name: "X/Twitter Analytics",
    prefix: "/api/x/analytics",
    endpointCount: 6,
    description: "Twitter engagement metrics, posting stats, connection status",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/x/analytics/connection",
  },
  {
    name: "Auto-Reply",
    prefix: "/api/auto-reply",
    endpointCount: 10,
    description: "X auto-reply engine — settings, config CRUD, activity log",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/auto-reply/settings",
  },
  {
    name: "Canva OAuth",
    prefix: "/api/canva/oauth",
    endpointCount: 6,
    description: "Canva Connect API OAuth and design listing",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/canva/oauth/status",
  },
  {
    name: "Moltbook",
    prefix: "/api/moltbook",
    endpointCount: 7,
    description: "Moltbook AI social network — posts, engagement, feed",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/moltbook/stats",
  },
  {
    name: "Partners",
    prefix: "/api/partners",
    endpointCount: 10,
    description: "AEO partner network — CRUD, metrics, dashboard",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/partners",
  },
  {
    name: "Partner Sites",
    prefix: "/api/partners/:slug/site",
    endpointCount: 8,
    description: "Partner microsite config, deployment, content publishing",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Site Metrics",
    prefix: "/api/site-metrics",
    endpointCount: 2,
    description: "coherencedaddy.com daily analytics ingestion",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Structure",
    prefix: "/api/structure",
    endpointCount: 3,
    description: "Company architecture diagram (Mermaid, versioned)",
    authType: "authenticated",
    category: "integrations",
    pingUrl: "/api/health/readiness",
  },

  // ── Public (no auth) ─────────────────────────────────────────────────
  {
    name: "Public Reels",
    prefix: "/api/reels",
    endpointCount: 5,
    description: "Public visual content — stream, download, thumbnails",
    authType: "public",
    category: "public",
    pingUrl: "/api/reels",
  },
  {
    name: "Partner Redirects",
    prefix: "/api/go",
    endpointCount: 1,
    description: "Click-tracking redirects for partner links",
    authType: "public",
    category: "public",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Partner Directory",
    prefix: "/api/partner-directory",
    endpointCount: 1,
    description: "Public partner business directory listing",
    authType: "public",
    category: "public",
    pingUrl: "/api/partner-directory",
  },
  {
    name: "Partner Site Feeds",
    prefix: "/api/partner-sites",
    endpointCount: 1,
    description: "Public RSS-style feeds for partner microsites",
    authType: "public",
    category: "public",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "Sitemaps",
    prefix: "/sitemap",
    endpointCount: 4,
    description: "XML sitemaps for search engines (pages, intel, reels)",
    authType: "public",
    category: "public",
    pingUrl: "/api/health/readiness",
  },
  {
    name: "LLM Config",
    prefix: "/api/llms",
    endpointCount: 3,
    description: "Agent configuration files for LLM adapters",
    authType: "public",
    category: "public",
    pingUrl: "/api/llms/agent-configuration.txt",
  },

  // ── System ────────────────────────────────────────────────────────────
  {
    name: "System Health",
    prefix: "/api/system-health",
    endpointCount: 6,
    description: "VPS monitoring, evals, alerts, logs, service status",
    authType: "authenticated",
    category: "system",
    pingUrl: "/api/system-health/overview",
  },
  {
    name: "System Crons",
    prefix: "/api/system-crons",
    endpointCount: 3,
    description: "Cron job listing, toggling, and manual triggering",
    authType: "authenticated",
    category: "system",
    pingUrl: "/api/system-crons",
  },
  {
    name: "Instance Settings",
    prefix: "/api/instance",
    endpointCount: 5,
    description: "General and experimental instance configuration",
    authType: "authenticated",
    category: "system",
    pingUrl: "/api/instance/settings/general",
  },
  {
    name: "Sidebar Badges",
    prefix: "/api/sidebar-badges",
    endpointCount: 1,
    description: "Sidebar notification badge counts",
    authType: "authenticated",
    category: "system",
    pingUrl: "/api/health/readiness",
  },

  // ── Plugins ───────────────────────────────────────────────────────────
  {
    name: "Plugins",
    prefix: "/api/plugins",
    endpointCount: 22,
    description: "Plugin lifecycle, tools, jobs, config, webhooks, dashboards",
    authType: "authenticated",
    category: "plugins",
    pingUrl: "/api/plugins",
  },
  {
    name: "Plugin UI",
    prefix: "/_plugins",
    endpointCount: 1,
    description: "Static file serving for plugin UIs",
    authType: "public",
    category: "plugins",
    pingUrl: "/api/health/readiness",
  },
];

/** Total number of registered endpoints across all groups */
export function getTotalEndpointCount(): number {
  return API_REGISTRY.reduce((sum, g) => sum + g.endpointCount, 0);
}
